language: go
go:
  - tip
before_install:
  - go get github.com/PuerkitoBio/goquery
  - go get github.com/Sirupsen/logrus
  - go get github.com/howeyc/gopass
  - go get github.com/ogier/pflag
  - go get github.com/mitchellh/gox
  - gox -build-toolchain -osarch="darwin/amd64 linux/amd64 windows/amd64"

script: make
deploy:
  provider: releases
  api_key:
    secure: Z55l9blwOv870mSOatQIKDkKL8UMBfuvTOj+RYyPC80W+IoAspomgS9yK2dHwcWoR2n2M5WwCLRcKYqQu5UHpqeGr4LnmlhyeWoA0fbRqYq+4IRG/xC6qfp99r9NTKjW9GHz7ThRiJBTrYbVve5Rc8wnD9SmAr5zSXufMseo/KU=
  file:
    - bin/windows/conoha.zip
    - bin/darwin/conoha.gz
    - bin/linux/conoha.gz

  skip_cleanup: true
  all_branches: true
  on:
    tags: true
    repo: hironobu-s/conoha-vps
