language: go
script: make
deploy:
  provider: releases
  api_key:
    secure: Z55l9blwOv870mSOatQIKDkKL8UMBfuvTOj+RYyPC80W+IoAspomgS9yK2dHwcWoR2n2M5WwCLRcKYqQu5UHpqeGr4LnmlhyeWoA0fbRqYq+4IRG/xC6qfp99r9NTKjW9GHz7ThRiJBTrYbVve5Rc8wnD9SmAr5zSXufMseo/KU=
  file:
    - bin/windows/conoha.zip
    - bin/darwin/conoha.gz
    - bin/linux/conoha.gz
  on:
    repo: hironobu-s/conoha-vps
